### ISSUE TITLE
Incorrect expression in condition

### ISSUE THREAD

**Issue by liuch** [orlo/pipedrive-crm-integration#1]
in this expression:
```` php
    if (json_last_error_msg() != JSON_ERROR_NONE) {
        throw new \Exception(json_last_error_msg());
    }
````
the json_last_error_msg function will never return JSON_ERROR_NONE. I think the json_last_error function should be used instead

I found that [here](https://github.com/orlo/pipedrive-crm-integration/blob/105f5c5c46119e7fc81d7d383b2ce20bd0d70802/public/index.php#L73) and [here](https://github.com/orlo/pipedrive-crm-integration/blob/105f5c5c46119e7fc81d7d383b2ce20bd0d70802/public/index.php#L109).

**Comment by DavidGoodwin** [comment]
Thank you! 

This code isn't actively maintained - but I've given it a quick once over, fixed the issue you highlighted above, and added psalm etc which might help catch similar errors if they happen in the future.
